apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: murmuler-main-db-pvc
spec:
 accessModes:
 - ReadWriteMany
 resources:
  requests:
   storage: 3G
 storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: murmuler-cs-db-pvc
spec:
 accessModes:
 - ReadWriteMany
 resources:
  requests:
   storage: 3G
 storageClassName: ""
