apiVersion: v1
kind: Service
metadata:
 name: murmuler-main-db
spec:
 type: NodePort
 ports:
 - port: 9000
   targetPort: 3306
   nodePort: 32000
 selector:
  app: mysql-main

---

apiVersion: v1
kind: Service
metadata:
 name: murmuler-cs-db
spec:
 type: NodePort
 ports:
 - port: 9001
   targetPort: 3306
   nodePort: 32001
 selector:
  app: mysql-cs
