apiVersion: v1
kind: Service
metadata:
 name: was-cs
spec:
 ports:
 - name: was-cs
   port: 8080
   targetPort: was-cs
 selector:
  app: was-cs

---

apiVersion: v1
kind: Service
metadata:
 name: was-main
spec:
 ports:
 - name: was-main
   port: 8080
   targetPort: was-main
 selector:
  app: was-main
