apiVersion: v1
kind: PersistentVolume
metadata:
 name: murmuler-db-pv
spec:
 capacity:
  storage: 5G
 accessModes:
  - ReadWriteMany
 local:
  path: /murmuler-volume
 nodeAffinity:
  required:
   nodeSelectorTerms:
   - matchExpressions:
     - {key: kubernetes.io/hostname, operator: In, values: [k8s-master]}
