apiVersion: v1
kind: PersistentVolume
metadata:
 name: murmuler-file-pv
 labels:
  volume: murmuler-file-pv
spec:
 capacity:
  storage: 3G
 accessModes:
 - ReadWriteMany
 volumeMode: Filesystem
 mountOptions:
  - hard
  - nfsvers=4.1
 nfs:
  path: /root/murmuler
  server: 192.168.122.1

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: murmuler-file-pvc
spec:
 accessModes:
 - ReadWriteMany
 resources:
  requests:
   storage: 3G
 storageClassName: ""
 selector:
  matchLabels:
   volume: murmuler-file-pv

