apiVersion: v1
kind: PersistentVolume
metadata:
 name: murmuler-main-file-pv
spec:
 capacity:
  storage: 3G
 accessModes:
 - ReadWriteMany
 local:
  path: /root/murmuler
 nodeAffinity:
  required:
   nodeSelectorTerms:
   - matchExpressions:
     - {key: kubernetes.io/hostname, operator: In, values: [k8s-node1, k8s-node2]}

