apiVersion: v1
kind: Service
metadata:
 name: murmuler-main-db
spec:
 ports:
 - port: 3306
 selector:
  app: mysql_main

---

apiVersion: v1
kind: Service
metadata:
 name: murmuler-cs-db
spec:
 ports:
 - port: 3306
 selector:
  app: mysql_cs

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql-main
spec:
 selector:
  matchLabels:
   app: mysql-main
 strategy:
  type: Recreate
 template:
  metadata:
   labels:
    app: mysql-main
  spec:
   containers:
   - image: mysql:5.6
     name: mysql-main
     env:
     - name: MYSQL_ROOT_PASSWORD
       value: password
#       valueFrom:
#        secretKeyRef:
#         name: mysql-pass
#         key: password
     ports:
     - containerPort: 3306
       name: mysql-main
     volumeMounts:
     - name: murmuler-main-volume
       mountPath: /var/lib/mysql
   volumes:
   - name: murmuler-main-volume
     persistentVolumeClaim:
      claimName: murmuler-main-db-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql-cs
spec:
 selector:
  matchLabels:
   app: mysql-cs
 strategy:
  type: Recreate
 template:
  metadata:
   labels:
    app: mysql-cs
  spec:
   containers:
   - image: mysql:5.6
     name: mysql-cs
     env:
     - name: MYSQL_ROOT_PASSWORD
       value: password
#       valueFrom:
#        secretKeyRef:
#         name: mysql-pass
#         key: password
     ports:
     - containerPort: 3306
       name: mysql-cs
     volumeMounts:
     - name: murmuler-cs-volume
       mountPath: /var/lib/mysql
   volumes:
   - name: murmuler-cs-volume
     persistentVolumeClaim:
      claimName: murmuler-cs-db-pvc

